"""Template generation for evidence-based release decisions."""

from __future__ import annotations


TEMPLATE = """\
# Scoped AI Release Decision Configuration
# Generated by release-checklist init
#
# This is a structure for a bounded decision record. Replace every placeholder,
# derive gates from the real use case and harm model, and cite versioned evidence.
# A valid file is not proof of safety, compliance, or release readiness.

metadata:
  project: "YOUR_PROJECT_NAME"
  version: "0.1.0"
  environment: "staging"
  risk_classification: "medium"
  domain_context: "{domain_context}"
  decision_scope: "[TBD: users, data, tools, permissions, geography, and rollout stage]"
  decision_owner: "[TBD: person with authority for this bounded decision]"
  evidence_cutoff: "[TBD: YYYY-MM-DD]"

decision:
  outcome: "defer"
  rationale: "[TBD: why this outcome follows from the current evidence]"
  blockers: []
  required_actions: []
  conditions: []
  evidence_gaps:
    - "[TBD: evidence required before a release decision]"
  residual_risks: []

# status: pass | fail | partial | not_tested | not_applicable
# hard_gate: true means the proposition is non-compensable for this scope.
# A pass or not_applicable status must cite evidence. Not applicable also needs
# a scoped rationale in limitation.
gates:
  - id: "SCOPE-001"
    question: "Is the reviewed population, data, tool, permission, and environment scope explicit?"
    hard_gate: true
    status: "not_tested"
    evidence: []
    owner: "[TBD]"
    limitation: "[TBD]"

  - id: "AUTH-001"
    question: "Are identity, authorization, confirmation, and action boundaries enforced for the reviewed scope?"
    hard_gate: true
    status: "not_tested"
    evidence: []
    owner: "[TBD]"
    limitation: "[TBD]"

  - id: "EVAL-001"
    question: "Does current evaluation evidence support the stated decision and disclose coverage and uncertainty?"
    hard_gate: false
    status: "not_tested"
    evidence: []
    owner: "[TBD]"
    limitation: "[TBD]"

  - id: "OPS-001"
    question: "Can the reviewed system be monitored, stopped, contained, recovered, and supported?"
    hard_gate: true
    status: "not_tested"
    evidence: []
    owner: "[TBD]"
    limitation: "[TBD]"
"""


# Compatibility surface for callers that imported these names. All variants
# use the same domain-neutral contract; domain labels do not inject obligations.
GENERAL_TEMPLATE = TEMPLATE.format(domain_context="general")
HEALTHCARE_TEMPLATE = TEMPLATE.format(domain_context="healthcare")
FINANCE_TEMPLATE = TEMPLATE.format(domain_context="finance")
TEMPLATES = {
    "general": GENERAL_TEMPLATE,
    "healthcare": HEALTHCARE_TEMPLATE,
    "finance": FINANCE_TEMPLATE,
    "insurance": TEMPLATE.format(domain_context="insurance"),
    "government": TEMPLATE.format(domain_context="government"),
}


def get_template(domain_context: str) -> str:
    """Return a domain-labelled template without injecting domain-specific gates."""
    normalized = (domain_context or "general").strip().lower()
    if normalized in TEMPLATES:
        return TEMPLATES[normalized]
    return TEMPLATE.format(domain_context=normalized)
